upstream node_servers {
  server server:$NODE_SERVER_LOCAL_PORT;
}

server {
  listen $NGINX_DOCKER_PORT;

  # Serve backend
  location /api/ {
    proxy_pass http://node_servers/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
  }
}
# Create an upstream node_servers block to define the group of servers listening on local port 3000.
# You will see later in the docker-compose setup that we did not define a specific port for each server instance,
# allowing Docker to dynamically assign ports and manage load balancing.